ci: jest report jest-junit added

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -9,27 +9,13 @@ on:
 
   # Triggers the workflow on push or pull request events but only for the main branch
   push:
-    branches:
-      - master
-      - main
-      - dev
-      - dev-*
-      - rel
-      - rel-*
-      - "*-rel-*"
+    branches: [master, main, dev, dev-*, rel, rel-*, "*-rel-*"]
   pull_request:
-    branches:
-      - master
-      - main
-      - dev
-      - dev-*
-      - rel
-      - rel-*
-      - "*-rel-*"
+    branches: [master, main, dev, dev-*, rel, rel-*, "*-rel-*"]
 
 env:
-  REPO_NAME: nodejs-ci-cd     # Set this to your application's name
-  REPO_PACKAGE_PATH: .        # Set this to the path to your web app project, defaults to the repository root
+  REPO_NAME: nodejs-ci-cd # Set this to your application's name
+  REPO_PACKAGE_PATH: . # Set this to the path to your web app project, defaults to the repository root
 
 permissions:
   contents: read
@@ -56,9 +42,18 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-          # node-version: ${{ env.NODE_VERSION }}
           cache: "npm"
+
       - name: Install dependencies
         run: npm ci
+
       - name: Run tests
         run: npm test
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: JEST Tests                # Name of the check run which will be created
+          path: test-reports/junit.xml    # Path to test results
+          reporter: jest-junit            # Format of test results
